# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.UUIDField(default=uuid.uuid4, help_text='ID único para el usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.BigIntegerField(help_text='Cedula de identidad')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
                ('contraseña', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
