# Generated by Django 2.2 on 2019-05-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_tecnico', models.IntegerField()),
                ('valor_negocio', models.IntegerField()),
                ('prioridad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_breve', models.CharField(blank=True, max_length=100)),
                ('tiempo_estimado', models.IntegerField(help_text='El valor ingresado serà en horas')),
                ('criterio_aceptacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
