# Generated by Django 2.2 on 2019-05-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejecucion', '0002_auto_20190509_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStory',
        ),
    ]
