# Generated by Django 2.2 on 2019-05-04 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion_breve', models.CharField(max_length=100)),
                ('descripcion_detallada', models.TextField(max_length=500)),
                ('estado', models.CharField(choices=[('to_do', 'En Planificacion'), ('doing', 'En Ejecucion'), ('done', 'Hecho')], default='to_do', max_length=5)),
                ('miembros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomProyecto',
            fields=[
                ('proyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='definicion.Proyecto')),
            ],
            bases=('definicion.proyecto',),
        ),
    ]
