# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(verbose_name='fecha_de_inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha_de_finalizacion')),
                ('descripcion_breve', models.CharField(max_length=100)),
                ('descripcion_detallada', models.TextField(max_length=1000)),
                ('estado', models.CharField(blank=True, choices=[('TO_DO', 'En planificacion'), ('DOING', 'En ejecucion'), ('DONE', 'Terminado')], default='Planificacion', help_text='Estado actual del Proyecto', max_length=5)),
                ('miembros', models.ManyToManyField(to='administracion.Usuario')),
            ],
        ),
    ]
