# Generated by Django 2.2 on 2019-05-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definicion', '0004_auto_20190506_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='miembros',
        ),
    ]
