# Generated by Django 2.2 on 2019-05-10 07:02

import definicion.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definicion', '0005_remove_proyecto_miembros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'sprint',
                'verbose_name_plural': 'sprints',
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('list_all_projects', 'listar los proyectos disponibles'), ('view_project', 'ver el proyecto'), ('aprobar_proyecto', 'aprobar el proyecto'), ('create_sprint', 'agregar sprint'), ('edit_sprint', 'editar sprint'), ('remove_sprint', 'eliminar sprint'), ('create_flujo', 'agregar flujo'), ('edit_flujo', 'editar flujo'), ('remove_flujo', 'eliminar flujo'), ('create_userstory', 'agregar userstory'), ('edit_userstory', 'editar userstory'), ('remove_userstory', 'eliminar userstory'), ('prioritize_userstory', 'asignar prioridad a userstories'), ('registraractividad_userstory', 'registrar avances en userstories'), ('aprobar_userstory', 'aprobar userstories completados'), ('cancelar_userstory', 'cancela userstories completados'))},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='duracion_sprint',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField(choices=[(0, 'Baja'), (1, 'Media'), (2, 'Alta')], default=0)),
                ('valor_negocio', models.IntegerField()),
                ('valor_tecnico', models.IntegerField()),
                ('tiempo_estimado', models.PositiveIntegerField()),
                ('tiempo_registrado', models.PositiveIntegerField(default=0)),
                ('ultimo_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'En curso'), (2, 'Pendiente Aprobacion'), (3, 'Aprobado'), (4, 'Cancelado')], default=0)),
                ('estado_fase', models.IntegerField(choices=[(0, 'ToDo'), (1, 'Doing'), (2, 'Done')], default=0)),
                ('desarrollador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='definicion.Fase')),
                ('proyecto', models.ForeignKey(blank=True, null=definicion.models.Fase, on_delete=django.db.models.deletion.SET_NULL, to='definicion.Proyecto')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='definicion.Sprint')),
            ],
            options={
                'verbose_name_plural': 'user stories',
                'permissions': (('edit_my_userstory', 'editar mis userstories'), ('registraractividad_my_userstory', 'registrar avances en mis userstories')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='definicion.Proyecto'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje de descripcion de los avances o motivo de cancelacion', null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiempo_registrado', models.IntegerField(default=0)),
                ('horas_a_registrar', models.IntegerField(default=0)),
                ('estado', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'En curso'), (2, 'Pendiente Aprobacion'), (3, 'Aprobado'), (4, 'Cancelado')], default=0)),
                ('estado_fase', models.IntegerField(choices=[(0, 'ToDo'), (1, 'Doing'), (2, 'Done')], null=True)),
                ('desarrollador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definicion.Fase')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definicion.Sprint')),
                ('user_story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definicion.UserStory')),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='definicion.Proyecto')),
            ],
            options={
                'verbose_name_plural': 'flujos',
                'permissions': (('add_flow_template', 'agregar plantilla de flujo'), ('change_flow_template', 'editar plantilla de flujo'), ('delete_flow_template', 'eliminar plantilla de flujo')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='fase',
            name='flujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='definicion.Flujo'),
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('filename', models.CharField(editable=False, max_length=100, null=True)),
                ('binario', models.BinaryField(blank=True, null=True)),
                ('content_type', models.CharField(editable=False, max_length=50, null=True)),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('img', 'Imagen'), ('text', 'Texto'), ('misc', 'Otro'), ('src', 'Codigo')], default='misc', max_length=10)),
                ('lenguaje', models.CharField(choices=[('clike', 'C'), ('python', 'Python'), ('ruby', 'Ruby'), ('css', 'CSS'), ('php', 'PHP'), ('scala', 'Scala'), ('sql', 'SQL'), ('bash', 'Bash'), ('javascript', 'JavaScript'), ('markup', 'Markup')], max_length=10, null=True)),
                ('user_story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='definicion.UserStory')),
            ],
        ),
        migrations.AlterOrderWithRespectTo(
            name='fase',
            order_with_respect_to='flujo',
        ),
    ]
